var vizup=vizup||{};vizup.LODChain=function(a,c){THREE.Object3D.call(this);this.location=c||"";this.modelName=a&&0<a.length?a:"Vizup LOD sample";this.lods=[];this.currentLODIndex=-1;this.stillLoading=!0;this.wireframeMode=this.shadingMode=0;this.npCenter=this.npScale=void 0};vizup.LODChain.prototype=Object.create(THREE.Object3D.prototype);vizup.LODChain.NAMETAG_LOD="Vizup-LOD";vizup.LODChain.NAMETAG_BUFFER_MESH="Vizup-Buffer-Mesh";vizup.LODChain.NAMETAG_CLASSIC_MESH="Vizup-Classic-Mesh";
vizup.LODChain.NAMETAG_DEBUG="Vizup-DEbug";vizup.LODChain.prototype.loadChain=function(a,c){this.lods=Array(a.length);this.stopIndex=void 0==c?a.length-1:0>c?a.length+c:c;for(var d=0;d<a.length;d++)this.load(d,this.location+a[d],1/(a.length-d));log.info("vizup.LODChain - LOD chain has been put in loading queue: "+a.length+" stop index: "+this.stopIndex)};
vizup.LODChain.prototype.load=function(a,c,d){var m=this;(new THREE.CTMLoader).load(c,function(l){var p=l.attributes.position;p&&log.info("loaded CTM geometry ["+a+"] for "+c+" ratio: "+d+" vertices: "+p.numItems/3);l.name=c;l=m.createLOD(l);l.ratio=d||1;l.url=c;m.add(l);m.lods[a]=l;a>m.currentLODIndex&&a<=m.stopIndex&&m.activateLOD(a);a==m.lods.length-1&&(log.info("vizup.LODChain: last LOD has been loaded: "+a),m.stillLoading=!1,l=vizup.LODChain.createDebugGeometry(m.lods[0].bufferMesh),vizup.LODChain.normalizeMesh(l,
m.npScale,m.npCenter),m.add(l))},{useWorker:!0})};
vizup.LODChain.prototype.createLOD=function(a){var c=new THREE.Object3D;c.name=vizup.LODChain.NAMETAG_LOD;var d=new THREE.Mesh(a,a.attributes.color?vizup.LODChain.MATERIAL_COLORS:vizup.LODChain.MATERIAL_SHADING);d.name=vizup.LODChain.NAMETAG_BUFFER_MESH;d.visible=!1;log.debug("vizup.LODChain: created shading mesh: "+d.id+" for "+a.name);this.npScale||(this.npScale=vizup.LODChain.normalizationScale(a),log.debug("vizup.LODChain: computed scale: "+this.npScale));this.npCenter||(this.npCenter=vizup.LODChain.normalizationCenter(a),
log.debug("vizup.LODChain: computed center: "+this.npCenter));log.debug("VizupLOD: normalized meshes with scale: "+this.npScale+" center["+this.npCenter.x+","+this.npCenter.y+","+this.npCenter.z);vizup.LODChain.normalizeMesh(c,this.npScale,this.npCenter);c.add(d);c.bufferMesh=d;return c};
vizup.LODChain.prototype.activateLOD=function(a){if(0>a||a>this.lods-1)return log.error("LODChain.prototype.activateLOD: index out of bound: "+a),!1;log.debug("vizup.LODChain: de-activating: "+this.currentLODIndex+" activating: "+a);if(0<=this.currentLODIndex){var c=this.lods[this.currentLODIndex];vizup.LODChain.setLODVisibility(c,!1)}this.currentLODIndex=a;c=this.lods[this.currentLODIndex];vizup.LODChain.setLODVisibility(c,!0);vizup.LODChain.setLODShadingMode(c,this.shadingMode);return!0};
vizup.LODChain.prototype.activateNextLOD=function(a){if(0<a&&this.currentLODIndex<this.lods.length-1)a=1;else if(0>a&&0<this.currentLODIndex)a=-1;else return!1;return this.activateLOD(this.currentLODIndex+a)};vizup.LODChain.prototype.setShadingMode=function(a){this.shadingMode=a%vizup.LODChain.ShadingMaterials.length;0<=this.currentLODIndex&&vizup.LODChain.setLODShadingMode(this.lods[this.currentLODIndex],this.shadingMode)};
vizup.LODChain.prototype.toggleShadingMode=function(){this.setShadingMode(this.shadingMode+1)};vizup.LODChain.prototype.toggleWireframeMode=function(){log.warn("LODChain.prototype.toggleWireframeMode - not implemented")};
vizup.LODChain.prototype.getHUDInfo=function(){var a={},c=this.lods[this.currentLODIndex];c.parent&&c.parent.modelName&&(a.Model=c.parent.modelName);var d=c.bufferMesh.geometry.attributes.position;d&&(a.Vertices=d.numItems/3);(c=c.bufferMesh.geometry.attributes.index)?a.Triangles=c.numItems/3:d&&(a.Triangles=d.numItems/9);return a};
vizup.LODChain.createDebugGeometry=function(a){var c=new THREE.Object3D;c.name=vizup.LODChain.NAMETAG_DEBUG;var d=new THREE.BoxHelper;d.visible=!1;d.material.color=new THREE.Color(16711680);d.update(a);c.add(d);d=new THREE.AxisHelper(a.geometry.boundingSphere.radius/2);d.position.copy(a.geometry.boundingBox.center());d.visible=!1;c.add(d);return c};
vizup.LODChain.setLODVisibility=function(a,c){log.debug("VizupLOD: setting visibility: "+c+" for: "+a.id);a.traverse(function(a){a instanceof THREE.Object3D&&(a.visible=c)})};
vizup.LODChain.setLODShadingMode=function(a,c){var d=vizup.LODChain.ShadingMaterials[c%vizup.LODChain.ShadingMaterials.length];a.bufferMesh&&(d==vizup.LODChain.MATERIAL_COLORS&&void 0==a.bufferMesh.geometry.attributes.color&&(log.debug("vizup.LODChain.setLODShadingMode - color shading not supported for this mesh, LOD.id = "+a.id),d=vizup.LODChain.MATERIAL_SHADING),a.bufferMesh.setMaterial(d))};
vizup.LODChain.normalizationScale=function(a){a.boundingBox||a.computeBoundingBox();var c=0.5*(a.boundingBox.max.y-a.boundingBox.min.y);return 1E-4<c?c:a.boundingSphere.radius};vizup.LODChain.normalizationCenter=function(a){a.boundingBox||a.computeBoundingBox();return a.boundingBox.center()};vizup.LODChain.normalizeMesh=function(a,c,d){c=1E-5<c?1.4/c:1;a.scale.set(c,c,c);a.position.set(-d.x*c,-d.y*c,-d.z*c)};
vizup.LODChain.MATERIAL_SHADING=new THREE.MeshLambertMaterial({color:12303291,opacity:1,wireframe:!1,shading:THREE.FlatShading});vizup.LODChain.MATERIAL_NORMALS=new THREE.MeshNormalMaterial({shading:THREE.FlatShading});vizup.LODChain.MATERIAL_COLORS=new THREE.MeshLambertMaterial({color:13421772,side:THREE.DoubleSide,vertexColors:THREE.VertexColors,shading:THREE.FlatShading});vizup.LODChain.ShadingMaterials=[vizup.LODChain.MATERIAL_COLORS,vizup.LODChain.MATERIAL_SHADING,vizup.LODChain.MATERIAL_NORMALS];
vizup.LODChain.MATERIAL_WIREFRAME=new THREE.MeshBasicMaterial({color:1118481,transparent:!0,wireframe:!0});function testMesh(){return new THREE.Mesh(new THREE.SphereGeometry(20,12,12),vizup.LODChain.MATERIAL_WIREFRAME)};vizup=vizup||{};
vizup.HUD=function(){this.miCanvas=document.createElement("canvas");this.miCanvas.width=vizup.HUD.MI_SIZE.width;this.miCanvas.height=vizup.HUD.MI_SIZE.height;this.miContext=this.miCanvas.getContext("2d");this.miContext.font="Bold "+vizup.HUD.MI_FONT;this.miContext.fillStyle=vizup.HUD.MI_COLOR;this.miContext.textAlign="center";var a=20;this.miContext.fillText("Vizup",vizup.HUD.MI_SIZE.width/2,a);this.miContext.font=vizup.HUD.MI_FONT;this.miContext.fillText("The Ultimate 3D Optimization",vizup.HUD.MI_SIZE.width/
2,a+20);this.miTexture=new THREE.Texture(this.miCanvas);this.miTexture.needsUpdate=!0;a=new THREE.SpriteMaterial({map:this.miTexture,useScreenCoordinates:!0,alignment:THREE.SpriteAlignment.topLeft});this.miSprite=new THREE.Sprite(a);this.miSprite.scale.set(vizup.HUD.MI_SIZE.width,vizup.HUD.MI_SIZE.height,1)};vizup.HUD.prototype.toggle=function(){this.miSprite.visible=!this.miSprite.visible};
vizup.HUD.prototype.updateLODinfo=function(a){this.miContext.clearRect(0,0,this.miCanvas.width,this.miCanvas.height);this.miContext.font="Bold "+vizup.HUD.MI_FONT;this.miContext.fillStyle=vizup.HUD.MI_COLOR;this.miContext.textAlign="left";var c=20;this.miContext.fillText("(c) Vizup - Ultimate 3D Optimization",5,c);this.miContext.font=vizup.HUD.MI_FONT;var c=c+20,d;for(d in a){var m=a[d];void 0!=m&&(this.miContext.fillText(d+": "+m,5,c),c+=16,log.debug("printing: <"+d+": "+m+"> at: 5:"+c))}this.miTexture.needsUpdate=
!0};vizup.HUD.onLODChange=function(a){};vizup.HUD.MI_FONT="14px Arial";vizup.HUD.MI_COLOR="rgba( 85,85,85,0.95 )";vizup.HUD.MI_SIZE={width:250,height:150};THREE.TrackballControls=function(a,c){function d(a){!1!==b.enabled&&(window.removeEventListener("keydown",d),u=h,h===f.NONE)&&(a.keyCode!==b.keys[f.ROTATE]||b.noRotate?a.keyCode!==b.keys[f.ZOOM]||b.noZoom?a.keyCode!==b.keys[f.PAN]||b.noPan||(h=f.PAN):h=f.ZOOM:h=f.ROTATE)}function m(a){!1!==b.enabled&&(a.preventDefault(),a.stopPropagation(),h!==f.ROTATE||b.noRotate?h!==f.ZOOM||b.noZoom?h!==f.PAN||b.noPan||(g=b.getMouseOnScreen(a.clientX,a.clientY)):r=b.getMouseOnScreen(a.clientX,a.clientY):v=b.getMouseProjectionOnBall(a.clientX,
a.clientY))}function l(a){!1!==b.enabled&&(a.preventDefault(),a.stopPropagation(),h=f.NONE,document.removeEventListener("mousemove",m),document.removeEventListener("mouseup",l))}function p(a){if(!1!==b.enabled){a.preventDefault();a.stopPropagation();var c=0;a.wheelDelta?c=a.wheelDelta/40:a.detail&&(c=-a.detail/3);q.y+=0.01*c}}var b=this,f={NONE:-1,ROTATE:0,ZOOM:1,PAN:2,TOUCH_ROTATE:3,TOUCH_ZOOM:4,TOUCH_PAN:5};this.object=a;this.domElement=void 0!==c?c:document;this.enabled=!0;this.screen={width:0,
height:0,offsetLeft:0,offsetTop:0};this.radius=(this.screen.width+this.screen.height)/4;this.rotateSpeed=1;this.zoomSpeed=1.2;this.panSpeed=0.3;this.staticMoving=this.noPan=this.noZoom=this.noRotate=!1;this.dynamicDampingFactor=0.2;this.minDistance=0;this.maxDistance=Infinity;this.keys=[65,83,68];this.target=new THREE.Vector3;var k=new THREE.Vector3,h=f.NONE,u=f.NONE,s=new THREE.Vector3,t=new THREE.Vector3,v=new THREE.Vector3,q=new THREE.Vector2,r=new THREE.Vector2,n=0,e=0,w=new THREE.Vector2,g=new THREE.Vector2;
this.target0=this.target.clone();this.position0=this.object.position.clone();this.up0=this.object.up.clone();var y={type:"change"};this.handleResize=function(){this.screen.width=window.innerWidth;this.screen.height=window.innerHeight;this.screen.offsetLeft=0;this.screen.offsetTop=0;this.radius=(this.screen.width+this.screen.height)/4};this.handleEvent=function(a){if("function"==typeof this[a.type])this[a.type](a)};this.getMouseOnScreen=function(a,c){return new THREE.Vector2(0.5*((a-b.screen.offsetLeft)/
b.radius),0.5*((c-b.screen.offsetTop)/b.radius))};this.getMouseProjectionOnBall=function(a,c){var d=new THREE.Vector3((a-0.5*b.screen.width-b.screen.offsetLeft)/b.radius,(0.5*b.screen.height+b.screen.offsetTop-c)/b.radius,0),e=d.length();1<e?d.normalize():d.z=Math.sqrt(1-e*e);s.copy(b.object.position).sub(b.target);e=b.object.up.clone().setLength(d.y);e.add(b.object.up.clone().cross(s).setLength(d.x));e.add(s.setLength(d.z));return e};this.rotateCamera=function(){var a=Math.acos(t.dot(v)/t.length()/
v.length());if(a){var c=(new THREE.Vector3).crossVectors(t,v).normalize(),d=new THREE.Quaternion,a=a*b.rotateSpeed;d.setFromAxisAngle(c,-a);s.applyQuaternion(d);b.object.up.applyQuaternion(d);v.applyQuaternion(d);b.staticMoving?t.copy(v):(d.setFromAxisAngle(c,a*(b.dynamicDampingFactor-1)),t.applyQuaternion(d))}};this.zoomCamera=function(){if(h===f.TOUCH_ZOOM){var a=n/e;n=e;s.multiplyScalar(a)}else a=1+(r.y-q.y)*b.zoomSpeed,1!==a&&0<a&&(s.multiplyScalar(a),b.staticMoving?q.copy(r):q.y+=(r.y-q.y)*this.dynamicDampingFactor)};
this.panCamera=function(){var a=g.clone().sub(w);if(a.lengthSq()){a.multiplyScalar(s.length()*b.panSpeed);var c=s.clone().cross(b.object.up).setLength(a.x);c.add(b.object.up.clone().setLength(a.y));b.object.position.add(c);b.target.add(c);b.staticMoving?w=g:w.add(a.subVectors(g,w).multiplyScalar(b.dynamicDampingFactor))}};this.checkDistances=function(){b.noZoom&&b.noPan||(b.object.position.lengthSq()>b.maxDistance*b.maxDistance&&b.object.position.setLength(b.maxDistance),s.lengthSq()<b.minDistance*
b.minDistance&&b.object.position.addVectors(b.target,s.setLength(b.minDistance)))};this.update=function(){s.subVectors(b.object.position,b.target);b.noRotate||b.rotateCamera();b.noZoom||b.zoomCamera();b.noPan||b.panCamera();b.object.position.addVectors(b.target,s);b.checkDistances();b.object.lookAt(b.target);0<k.distanceToSquared(b.object.position)&&(b.dispatchEvent(y),k.copy(b.object.position))};this.reset=function(){u=h=f.NONE;b.target.copy(b.target0);b.object.position.copy(b.position0);b.object.up.copy(b.up0);
s.subVectors(b.object.position,b.target);b.object.lookAt(b.target);b.dispatchEvent(y);k.copy(b.object.position)};this.domElement.addEventListener("contextmenu",function(a){a.preventDefault()},!1);this.domElement.addEventListener("mousedown",function(a){!1!==b.enabled&&(a.preventDefault(),a.stopPropagation(),h===f.NONE&&(h=a.button),h!==f.ROTATE||b.noRotate?h!==f.ZOOM||b.noZoom?h!==f.PAN||b.noPan||(w=g=b.getMouseOnScreen(a.clientX,a.clientY)):q=r=b.getMouseOnScreen(a.clientX,a.clientY):t=v=b.getMouseProjectionOnBall(a.clientX,
a.clientY),document.addEventListener("mousemove",m,!1),document.addEventListener("mouseup",l,!1))},!1);this.domElement.addEventListener("mousewheel",p,!1);this.domElement.addEventListener("DOMMouseScroll",p,!1);this.domElement.addEventListener("touchstart",function(a){if(!1!==b.enabled)switch(a.touches.length){case 1:h=f.TOUCH_ROTATE;t=v=b.getMouseProjectionOnBall(a.touches[0].pageX,a.touches[0].pageY);break;case 2:h=f.TOUCH_ZOOM;var c=a.touches[0].pageX-a.touches[1].pageX;a=a.touches[0].pageY-a.touches[1].pageY;
e=n=Math.sqrt(c*c+a*a);break;case 3:h=f.TOUCH_PAN;w=g=b.getMouseOnScreen(a.touches[0].pageX,a.touches[0].pageY);break;default:h=f.NONE}},!1);this.domElement.addEventListener("touchend",function(a){if(!1!==b.enabled){switch(a.touches.length){case 1:t=v=b.getMouseProjectionOnBall(a.touches[0].pageX,a.touches[0].pageY);break;case 2:n=e=0;break;case 3:w=g=b.getMouseOnScreen(a.touches[0].pageX,a.touches[0].pageY)}h=f.NONE}},!1);this.domElement.addEventListener("touchmove",function(a){if(!1!==b.enabled)switch(a.preventDefault(),
a.stopPropagation(),a.touches.length){case 1:v=b.getMouseProjectionOnBall(a.touches[0].pageX,a.touches[0].pageY);break;case 2:var c=a.touches[0].pageX-a.touches[1].pageX;a=a.touches[0].pageY-a.touches[1].pageY;e=Math.sqrt(c*c+a*a);break;case 3:g=b.getMouseOnScreen(a.touches[0].pageX,a.touches[0].pageY);break;default:h=f.NONE}},!1);window.addEventListener("keydown",d,!1);window.addEventListener("keyup",function(a){!1!==b.enabled&&(h=u,window.addEventListener("keydown",d,!1))},!1);this.handleResize()};
THREE.TrackballControls.prototype=Object.create(THREE.EventDispatcher.prototype);THREE.CTMLoader=function(a){THREE.Loader.call(this,a)};THREE.CTMLoader.prototype=Object.create(THREE.Loader.prototype);
THREE.CTMLoader.prototype.loadParts=function(a,c,d){var m=this,l=new XMLHttpRequest,p=d.basePath?d.basePath:this.extractUrlBase(a);l.onreadystatechange=function(){if(4===l.readyState&&(200===l.status||0===l.status)){for(var a=JSON.parse(l.responseText),f=[],k=[],h=0,u=0;u<a.materials.length;u++)f[u]=THREE.Loader.prototype.createMaterial(a.materials[u],p);m.load(p+a.data,function(d){h+=1;k.push(d);h===a.offsets.length&&c(k,f)},{useWorker:d.useWorker,useBuffers:d.useBuffers,offsets:a.offsets})}};l.open("GET",
a,!0);l.overrideMimeType&&l.overrideMimeType("text/plain; charset=x-user-defined");l.setRequestHeader("Content-Type","text/plain");l.send(null)};
THREE.CTMLoader.prototype.load=function(a,c,d){var m=this,l=void 0!==d.offsets?d.offsets:[0],p=void 0!==d.useBuffers?d.useBuffers:!0,b=new XMLHttpRequest;b.onreadystatechange=function(){if(4===b.readyState)if(200===b.status||0===b.status){var f=b.responseText;if(d.useWorker){var k=new Worker("js/vizup-webw.js");k.onmessage=function(a){a=a.data;for(var b=0;b<a.length;b++){var d=a[b];p?m.createModelBuffers(d,c):m.createModelClassic(d,c)}};k.postMessage({data:f,offsets:l})}else for(k=0;k<l.length;k++){var h=
new CTM.Stream(f);h.offset=l[k];h=new CTM.File(h);p?m.createModelBuffers(h,c):m.createModelClassic(h,c)}}else console.error("Couldn't load ["+a+"] ["+b.status+"]");else 3!==b.readyState&&2===b.readyState&&b.getResponseHeader("Content-Length")};b.overrideMimeType("text/plain; charset=x-user-defined");b.open("GET",a,!0);b.send(null)};
THREE.CTMLoader.prototype.createModelBuffers=function(a,c){var d=function(){this.materials=[];THREE.BufferGeometry.call(this);var c=a.body.indices,d=a.body.vertices,p=a.body.normals,b,f;void 0!==a.body.uvMaps&&0<a.body.uvMaps.length&&(b=a.body.uvMaps[0].uv);void 0!==a.body.attrMaps&&(0<a.body.attrMaps.length&&"Color"===a.body.attrMaps[0].name)&&(f=a.body.attrMaps[0].attr);var k=new Uint32Array(c.length),h=new Float32Array(d.length),u,s,t;p&&(u=new Float32Array(p.length));b&&(s=new Float32Array(b.length));
f&&(t=new Float32Array(f.length));for(var v={},q=0,r=function(a){if(void 0===v[a]){v[a]=q;var c=3*a,e=3*a+1,g=3*a+2,n=3*q,r=3*q+1,k=3*q+2;h[n]=d[c];h[r]=d[e];h[k]=d[g];p&&(u[n]=p[c],u[r]=p[e],u[k]=p[g]);b&&(s[2*q]=b[2*a],s[2*q+1]=b[2*a+1]);f&&(t[4*q]=f[4*a],t[4*q+1]=f[4*a+1],t[4*q+2]=f[4*a+2],t[4*q+3]=f[4*a+3]);q+=1}},n,e,w,g=0;g<c.length;g+=3)n=c[g],e=c[g+1],w=c[g+2],r(n),r(e),r(w),k[g]=v[n],k[g+1]=v[e],k[g+2]=v[w];c=k;d=h;p&&(p=u);b&&(b=s);f&&(f=t);this.offsets=[];k=c;r=0;e=d.length;w=0;n=e;for(g=
0;g<k.length;){for(var y=0;3>y;++y){var z=k[g++];z<e&&(e=z);z>w&&(w=z)}if(65535<w-e){g-=3;for(e=r;e<g;++e)k[e]-=n;this.offsets.push({start:r,count:g-r,index:n});r=g;e=d.length;w=0}n=e}for(e=r;e<g;++e)k[e]-=n;this.offsets.push({start:r,count:g-r,index:n});c=new Uint16Array(c);g=this.attributes;g.index={itemSize:1,array:c,numItems:c.length};g.position={itemSize:3,array:d,numItems:d.length};void 0!==p&&(g.normal={itemSize:3,array:p,numItems:p.length});void 0!==b&&(g.uv={itemSize:2,array:b,numItems:b.length});
void 0!==f&&(g.color={itemSize:4,array:f,numItems:f.length})};d.prototype=Object.create(THREE.BufferGeometry.prototype);d=new d;void 0===d.attributes.normal&&d.computeVertexNormals();c(d)};
THREE.CTMLoader.prototype.createModelClassic=function(a,c){var d=function(){function c(a){var b,d,n,e,h=a.length;for(e=0;e<h;e+=3)b=a[e],d=a[e+1],n=a[e+2],f.push(b,d,n)}function d(a){var b,c,f,e,k=a.length;for(e=0;e<k;e+=4){b=a[e];c=a[e+1];f=a[e+2];var g=new THREE.Color;g.setRGB(b,c,f);h.push(g)}}function p(a){var b,c,d,e=a.length;for(d=0;d<e;d+=2)b=a[d],c=a[d+1],k.push(b,c)}var b=this;b.materials=[];THREE.Geometry.call(this);var f=[],k=[],h=[];(function(a){var c,d,f,e,h=a.length;for(e=0;e<h;e+=3)c=
a[e],d=a[e+1],f=a[e+2],b.vertices.push(new THREE.Vector3(c,d,f))})(a.body.vertices);void 0!==a.body.normals&&c(a.body.normals);void 0!==a.body.uvMaps&&0<a.body.uvMaps.length&&p(a.body.uvMaps[0].uv);void 0!==a.body.attrMaps&&(0<a.body.attrMaps.length&&"Color"===a.body.attrMaps[0].name)&&d(a.body.attrMaps[0].attr);var u=0<f.length?!0:!1,s=0<k.length?!0:!1,t=0<h.length?!0:!1;(function(a){var c,d,n,e,l,g,m,p,x,C=a.length;for(x=0;x<C;x+=3){c=a[x];d=a[x+1];n=a[x+2];if(u){e=b;m=c;p=d;l=n;var A=f[3*d],D=
f[3*d+1],E=f[3*d+2],B=f[3*n],F=f[3*n+1],G=f[3*n+2];g=new THREE.Vector3(f[3*c],f[3*c+1],f[3*c+2]);A=new THREE.Vector3(A,D,E);B=new THREE.Vector3(B,F,G);m=new THREE.Face3(m,p,l,[g,A,B],null,0)}else e=b,m=new THREE.Face3(c,d,n,null,null,0);e.faces.push(m);e=m;t&&(e.vertexColors[0]=h[c],e.vertexColors[1]=h[d],e.vertexColors[2]=h[n]);s&&(e=k[2*c],c=k[2*c+1],l=k[2*d],g=k[2*d+1],m=k[2*n],p=k[2*n+1],n=b.faceVertexUvs[0],d=l,l=g,g=[],g.push(new THREE.Vector2(e,c)),g.push(new THREE.Vector2(d,l)),g.push(new THREE.Vector2(m,
p)),n.push(g))}})(a.body.indices);this.computeCentroids();this.computeFaceNormals()};d.prototype=Object.create(THREE.Geometry.prototype);c(new d)};var log=log4javascript.getDefaultLogger(),vizupWebRenderer,vizupWebCamera,vizupWebControls,vizupHUD,vizupWebScene,vizupWebModel;
function vizupWebView_init(a){var c=document.getElementById(a);if(!c)return log.error("VizupWebView: cant find container: "+a),!1;vizupWebRenderer=new THREE.WebGLRenderer({antialias:!0});vizupWebRenderer.setSize(c.offsetWidth,c.offsetHeight);c.appendChild(vizupWebRenderer.domElement);vizupWebScene=new THREE.Scene;vizupWebCamera=new THREE.PerspectiveCamera(50,c.offsetWidth/c.offsetHeight,0.1,1E3);vizupWebCamera.position.z=5;vizupWebScene.add(vizupWebCamera);vizupWebView_addLights();vizupWebView_addControls(c);
vizupHUD=new vizup.HUD;vizupWebScene.add(vizupHUD.miSprite);log.info("vizupWebView - initialized.");return!0}function vizupWebView_addLights(){var a=new THREE.AmbientLight(7368800);vizupWebScene.add(a);a=new THREE.PointLight(16777215,1,100);a.position.set(-5,5,10);vizupWebCamera.add(a)}
function vizupWebView_addControls(a){vizupWebControls=new THREE.TrackballControls(vizupWebCamera,vizupWebRenderer.domElement);vizupWebControls.target.set(0,0,0);document.addEventListener("keydown",vizupWebView_onKeyPress,!1)}function vizupWebView_animate(){requestAnimationFrame(vizupWebView_animate);vizupWebControls.update();vizupWebRenderer.render(vizupWebScene,vizupWebCamera)}
function vizupWebView_loadModel(a){vizupWebModel=new vizup.LODChain(a.name,a.url);vizupWebModel.loadChain(a.lods,a.showIndex);a.rotation&&(vizupWebModel.rotation.set(a.rotation[0],a.rotation[1],a.rotation[2]),log.debug("vizupWebView_loadModel - applied demo ratation: [ "+a.rotation[0]+", "+a.rotation[1]+", "+a.rotation[2]+" ]"));vizupWebScene.add(vizupWebModel)}
function vizupWebView_onKeyPress(a){log.trace("key pressed: "+a.keyCode);switch(a.keyCode){case 190:case 39:vizupWebModel.activateNextLOD(1);vizupHUD.updateLODinfo(vizupWebModel.getHUDInfo());break;case 188:case 37:vizupWebModel.activateNextLOD(-1);vizupHUD.updateLODinfo(vizupWebModel.getHUDInfo());break;case 83:vizupWebModel.toggleShadingMode();break;case 82:case 48:vizupWebControls.reset();break;case 73:vizupHUD.toggle(),vizupHUD.updateLODinfo(vizupWebModel.getHUDInfo())}};
